Db/models service attachment feature
SimplySmartTech/simplysmart-web pull request #2
Opened 2022-09-01 12:50 UTC by Chinmay891

Created three models for service page. Lock files not included.

2022-09-02 12:23 UTC, rutujanirmal requested changes

2022-09-02 12:23 UTC, rutujanirmal commented on db/migrate/20220901115806_create_features.rb
> +      t.string :feature_name
it should be only name not feature_name

2022-09-02 12:23 UTC, rutujanirmal commented on db/migrate/20220901113844_create_attachments.rb
> +      t.string :image_url
rename this to attachement url to use it for other file types as well

2022-09-05 10:11 UTC, Chinmay891 commented on db/migrate/20220901113403_create_services.rb
> +      t.string :video_url
We just have 3 video URLs for 3 services, so it will be more easy to populate them this way.

2022-09-05 11:01 UTC, Chinmay891 commented on app/models/service.rb
> +    has_many :attachment
We give file name in has_many, plural form will refer to the table

2022-09-06 05:35 UTC, rutujanirmal commented on app/models/service.rb
> +    has_many :attachment
![image](https://user-images.githubusercontent.com/64598190/188554367-77486676-4dc1-4df3-907f-40f3ffb88e69.png)

2022-09-06 09:22 UTC, rutujanirmal commented on db/migrate/20220905102453_update_column_name.rb
> +class UpdateColumnName < ActiveRecord::Migration[7.0]
rollback and use proper naming for migrations

2022-09-06 12:14 UTC, rutujanirmal approved these changes

2022-09-06 12:23 UTC, merged